### ISSUE TITLE
Running xenial->bionic series upgrades does not install required charmhelpers

### ISSUE THREAD

**Issue by dparv** [juju-solutions/charm-ubuntu#14]
Units goes into error state with:

 File "./hooks/leader-settings-changed", line 9, in <module>
    basic.init_config_states()
  File "lib/charms/layer/basic.py", line 174, in init_config_states
    from charmhelpers.core import hookenv
ModuleNotFoundError: No module named 'charmhelpers'

Have to manually run "sudo pip install charmhelpers; sudo pip install charms.reactive" to fix it.

**Comment by kwmonroe** [comment]
Late to the party, but xenial support was recently dropped from this charm so I can't repro this failure.  I did confirm bionic->focal and focal->jammy upgrades work as expected with the current charm.
