### ISSUE TITLE
focal install fails

### ISSUE THREAD

**Issue by mthaddon** [juju-solutions/charm-ubuntu#15]
I get an install error using cs:ubuntu on focal: https://paste.ubuntu.com/p/3HMQsSCbhd/

**Comment by hloeung** [comment]
This is https://github.com/juju/charm-helpers/pull/423

**Comment by hloeung** [comment]
But yeah, the charm needs to be rebuilt bulling in the fix.

**Comment by mthaddon** [comment]
I tried rebuilding the charm as-is, pushing to the charmstore and deploying, and it failed in the same way for me (using cs:~mthaddon/ubuntu)

**Comment by johnsca** [comment]
The charm-helpers PR has been released in v0.20.9 and I verified that rebuilding the Ubuntu charm now fixes the issue. I don't have permissions to update cs:ubuntu, though, and @tvansteenburgh is out this week.

**Comment by mthaddon** [comment]
> I tried rebuilding the charm as-is, pushing to the charmstore and deploying, and it failed in the same way for me (using cs:~mthaddon/ubuntu)

I think the reason I was seeing this was local cache. If I build with --no-local-layers I also see the correct charmhelpers version. Thanks.

**Comment by mthaddon** [comment]
Confirming this has now been fixed.

**Comment by kwmonroe** [comment]
FYI, this went out in `cs:ubuntu-14`
