### ISSUE TITLE
cs:ubuntu-14 is affected by https://github.com/juju/charm-helpers/issues/433

### ISSUE THREAD

**Issue by xavpaice** [juju-solutions/charm-ubuntu#16]
Deploying cs:ubuntu-14 fails on Xenial due to https://github.com/juju/charm-helpers/issues/433.  A fix for that has been released, but we need to get cs:ubuntu rebuilt and released with the current layer-basic etc. in order to resolve this.

**Comment by auria** [comment]
@mthaddon would it be possible to release a new "charm build"? the issue causing this has been fixed and this charm needs to be rebuilt and released in order to make it work in trusty/xenial.

Thank you.

**Comment by kwmonroe** [comment]
Rebuilt to pick up latest charmhelpers.  Quick deployment on trusty/xenial/bionic/focal look good.  This has been pushed through stable in rev >= 15:

https://jaas.ai/ubuntu
