### ISSUE TITLE
empty status message

### ISSUE THREAD

**Issue by sajoupa** [juju-solutions/charm-ubuntu#24]
Hi,

Since https://github.com/juju-solutions/charm-ubuntu/commit/e3adefd24277d5a82d6df6dd97a644c839726ae0, the charm no longer sets the `ready` status message, only the `active` state.
Some tools rely on this message to detect that the unit is... well, that it's ready (in addition to being `active`).
Is this a regression, or should we consider that `active/""` is the new `active/ready` ?

Thanks.

**Comment by freyes** [comment]
This change broke the functional testing for graylog, virtually anyone using zaza and the ubuntu charm is seeing this regression. In the Support organization we see users/operators who get worried when they see charms don't a state nor workload message, so I don't think considering active/"" as the active/ready a good idea.

**Comment by kwmonroe** [comment]
Closing this out per https://github.com/juju-solutions/charm-ubuntu/pull/36#pullrequestreview-870738838.
