### ISSUE TITLE
Conflicting license information

### ISSUE THREAD

**Issue by paulgear** [juju-solutions/charm-ubuntu#4]
GPLv3 text does not an Apache 2.0 license make. :-)  http://bazaar.launchpad.net/~charmers/charms/precise/ubuntu/trunk/view/head:/copyright seems to indicate it was intended to be GPL...

**Comment by johnsca** [comment]
The Apache 2.0 license is more compatible with layered / reactive charms.  I don't see any conflicting info now, so I assume this has been resolved.
