### ISSUE TITLE
No support for ubuntu jammy in charmhub

### ISSUE THREAD

**Issue by freyes** [juju-solutions/charm-ubuntu#44]
Hello Everyone,

Is it possible to upload a new version of the ubuntu charm to charmhub?, ideally to latest/stable, but latest/edge would work for me as well, since at the moment it's not possible to deploy this charm on jammy.

Thanks,

**Comment by kwmonroe** [comment]
@freyes, though not recommended, you can use `--force` to workaround the series mismatch:

```bash
$ juju version
2.9.33-ubuntu-amd64

$ juju deploy ubuntu --series jammy
ERROR series "jammy" not supported by charm, supported series are: focal, bionic, xenial, trusty, precise, groovy, disco, cosmic, artful, vivid. Use --force to deploy the charm anyway.

$ juju deploy ubuntu --series jammy --force
Located charm "ubuntu" in charm-hub, revision 19
Deploying "ubuntu" from charm-hub charm "ubuntu", revision 19 in channel stable on jammy

$ juju run --unit ubuntu/0 -- cat /etc/issue
Ubuntu 22.04 LTS \n \l

$ juju status ubuntu
Model   Controller     Cloud/Region   Version   SLA          Timestamp
ubuntu  aws-us-east-1  aws/us-east-1  2.9.33.1  unsupported  10:17:04-05:00

App     Version  Status  Scale  Charm   Channel  Rev  Exposed  Message
ubuntu  22.04    active      1  ubuntu  stable    19  no       

Unit       Workload  Agent  Machine  Public address  Ports  Message
ubuntu/0*  active    idle   0        3.218.142.4            
```

I'll see if i can get the ubuntu charm updated for official support, but hopefully the above workaround is useful until then.

**Comment by mthaddon** [comment]
@kwmonroe the charm should already support jammy per https://github.com/juju-solutions/charm-ubuntu/pull/41, just that that version hasn't been released yet I think.

**Comment by kwmonroe** [comment]
[released](https://charmhub.io/ubuntu).  big ups to @addyess.
